import type { Fact } from "../../types/Fact";

export const animalFacts: Fact[] = [
    {
        id: 1,
        category: "Animals",
        title: "Naked Mole Rat Longevity",
        fact: "Naked mole rats can live up to 30 years, 10 times longer than similar-sized rodents. They show virtually no signs of aging and are resistant to cancer and many types of pain.",
        verified: true,
        source: "Science Magazine",
        year_discovered: 2002,
        interesting_rating: 9.1
    },
    {
        id: 2,
        category: "Animals",
        title: "Pistol Shrimp Sound",
        fact: "The pistol shrimp creates a bubble that, when it collapses, produces a sound louder than a gunshot and temperatures nearly as hot as the sun's surface for a fraction of a second.",
        verified: true,
        source: "Journal of Marine Biology",
        year_discovered: 2001,
        interesting_rating: 9.4
    },
    {
        id: 3,
        category: "Animals",
        title: "Mantis Shrimp Vision",
        fact: "Mantis shrimp have the most complex eyes in the animal kingdom, with 16 color receptors (humans have 3). They can see ultraviolet, infrared, and polarized light, and each eye moves independently.",
        verified: true,
        source: "Current Biology Journal",
        year_discovered: 2014,
        interesting_rating: 9.5
    },
    {
        id: 4,
        category: "Animals",
        title: "Axolotl Regeneration",
        fact: "The axolotl salamander can regenerate entire limbs, parts of its brain, heart, and even spinal cord without scarring. Scientists study them for potential applications in human regenerative medicine.",
        verified: true,
        source: "Developmental Biology Journal",
        year_discovered: 1964,
        interesting_rating: 9.3
    },
    {
        id: 5,
        category: "Animals",
        title: "Ant Strength",
        fact: "Ants can lift up to 50 times their body weight and pull up to 30 times their body weight. Proportionally, that would be like a human lifting a truck.",
        verified: true,
        source: "Journal of Biomechanics",
        year_discovered: 1996,
        interesting_rating: 8.7
    },
    {
        id: 6,
        category: "Animals",
        title: "Cheetah Acceleration",
        fact: "A cheetah can accelerate from 0 to 60 mph (96.5 km/h) in just three seconds, faster than most sports cars. Their top speed is about 70 mph (112.6 km/h).",
        verified: true,
        source: "National Geographic Research",
        year_discovered: 1997,
        interesting_rating: 9.0
    },
    {
        id: 7,
        category: "Animals",
        title: "Platypus Electricity Detection",
        fact: "Platypuses can detect electrical fields generated by muscular contractions of their prey. They close their eyes, ears, and nose when diving and hunt using only their bill's electroreceptors.",
        verified: true,
        source: "Australian Journal of Zoology",
        year_discovered: 1986,
        interesting_rating: 9.2
    },
    {
        id: 8,
        category: "Animals",
        title: "Mimic Octopus",
        fact: "The mimic octopus can impersonate up to 15 different species, including sea snakes, lionfish, flatfish, and jellyfish, changing its shape, color, and behavior to match the animal it's mimicking.",
        verified: true,
        source: "Marine Ecology Progress",
        year_discovered: 1998,
        interesting_rating: 9.6
    },
    {
        id: 9,
        category: "Animals",
        title: "Goat Pupils",
        fact: "Goats have rectangular pupils that give them a 320-330 degree field of vision, allowing them to see almost all around them without moving their heads, which helps detect predators.",
        verified: true,
        source: "Science Advances Journal",
        year_discovered: 2015,
        interesting_rating: 8.5
    },
    {
        id: 10,
        category: "Animals",
        title: "Tardigrade Radiation",
        fact: "Tardigrades (water bears) can survive in the vacuum of space and endure radiation levels 1,000 times greater than would kill a human. They can also survive being completely dried out for decades.",
        verified: true,
        source: "Astrobiology Journal",
        year_discovered: 2008,
        interesting_rating: 9.5
    },
    {
        id: 11,
        category: "Animals",
        title: "Arctic Fox Insulation",
        fact: "Arctic foxes' fur is so well-insulated that they don't begin to shiver until the temperature drops to -94°F (-70°C). Their body temperature doesn't start to drop until -112°F (-80°C).",
        verified: true,
        source: "Journal of Thermal Biology",
        year_discovered: 1986,
        interesting_rating: 8.9
    },
    {
        id: 12,
        category: "Animals",
        title: "Bombardier Beetle Defense",
        fact: "When threatened, the bombardier beetle mixes chemicals in its abdomen to create an explosive, boiling hot spray (212°F/100°C) that it can aim with accuracy at predators.",
        verified: true,
        source: "Science Journal",
        year_discovered: 1961,
        interesting_rating: 9.1
    },
    {
        id: 13,
        category: "Animals",
        title: "Penguin Pressure Resistance",
        fact: "Emperor penguins can dive to depths of 1,850 feet (565 meters) and withstand pressures of 40 times what humans experience at sea level without getting decompression sickness.",
        verified: true,
        source: "Marine Ecology Research",
        year_discovered: 1992,
        interesting_rating: 8.8
    },
    {
        id: 14,
        category: "Animals",
        title: "Shark Electrosensitivity",
        fact: "Sharks can detect electric fields as weak as 5 nanovolts per centimeter—about 5 millionths of a volt. This allows them to detect the heartbeat of prey hidden under the sand.",
        verified: true,
        source: "Journal of Experimental Biology",
        year_discovered: 1979,
        interesting_rating: 9.0
    },
    {
        id: 15,
        category: "Animals",
        title: "Hummingbird Metabolism",
        fact: "A hummingbird's heart beats up to 1,260 times per minute. They have the highest metabolic rate of any animal except insects, and would die within hours if they didn't feed regularly.",
        verified: true,
        source: "Ornithology Research",
        year_discovered: 1983,
        interesting_rating: 8.8
    },
    {
        id: 16,
        category: "Animals",
        title: "Chameleon Tongue",
        fact: "A chameleon's tongue can accelerate from 0 to 60 mph in 1/100th of a second, reaching its target in 0.07 seconds—faster than a fighter jet. The tongue can extend to twice the animal's body length.",
        verified: true,
        source: "Journal of Experimental Zoology",
        year_discovered: 2004,
        interesting_rating: 9.2
    },
    {
        id: 17,
        category: "Animals",
        title: "Bees' Gravity Detection",
        fact: "Honeybees can detect changes in gravity as small as 1/25th that of Earth's. They use this sensitivity to stay oriented when flying and to perform their intricate waggle dances.",
        verified: true,
        source: "Journal of Comparative Physiology",
        year_discovered: 2014,
        interesting_rating: 8.6
    },
    {
        id: 18,
        category: "Animals",
        title: "Hippo Sunscreen",
        fact: "Hippos secrete a reddish oily fluid often called 'blood sweat' that acts as a natural sunscreen and antibiotic, protecting their skin from sun damage and infections.",
        verified: true,
        source: "Nature Journal",
        year_discovered: 2004,
        interesting_rating: 8.5
    },
    {
        id: 19,
        category: "Animals",
        title: "Crocodile Stomach Acidity",
        fact: "Crocodiles have the most acidic stomach of any vertebrate, with a pH of less than 1. This allows them to digest bones, hooves, and horns, and even dissolve metal objects.",
        verified: true,
        source: "Journal of Experimental Biology",
        year_discovered: 2012,
        interesting_rating: 8.9
    },
    {
        id: 20,
        category: "Animals",
        title: "Bat Longevity",
        fact: "Bats live extraordinarily long lives compared to mammals of similar size. The Brandt's bat weighs just 4-8 grams but can live up to 41 years—equivalent to a human living 240 years.",
        verified: true,
        source: "PLOS ONE Journal",
        year_discovered: 2005,
        interesting_rating: 8.7
    },
    {
        id: 21,
        category: "Animals",
        title: "Sea Cucumber Defense",
        fact: "When threatened, some species of sea cucumbers expel their internal organs, including their intestines, lungs, and part of their reproductive organs, which then regrow within a few weeks.",
        verified: true,
        source: "Marine Biology Research",
        year_discovered: 1968,
        interesting_rating: 9.0
    },
    {
        id: 22,
        category: "Animals",
        title: "Peacock Spider Dance",
        fact: "Male peacock spiders perform elaborate mating dances with vibrant, iridescent abdominal flaps raised like a peacock's tail. They also use synchronized leg movements and vibrations to attract females.",
        verified: true,
        source: "Journal of Arachnology",
        year_discovered: 2008,
        interesting_rating: 8.8
    },
    {
        id: 23,
        category: "Animals",
        title: "Horned Lizard Blood Defense",
        fact: "When threatened, the Texas horned lizard can shoot blood from the corners of its eyes up to 4 feet (1.2 meters). The blood contains chemicals foul-tasting to predators like coyotes and wolves.",
        verified: true,
        source: "Herpetology Journal",
        year_discovered: 1967,
        interesting_rating: 9.3
    },
    {
        id: 24,
        category: "Animals",
        title: "Frog Freeze Survival",
        fact: "The wood frog can survive being frozen solid for weeks. Up to 65% of its body water turns to ice, its heart stops, and it stops breathing—only to thaw and hop away when spring arrives.",
        verified: true,
        source: "Journal of Experimental Biology",
        year_discovered: 1992,
        interesting_rating: 9.4
    },
    {
        id: 25,
        category: "Animals",
        title: "Spider Silk Strength",
        fact: "Spider silk is five times stronger than steel of the same diameter and more elastic than rubber. A strand thick enough to encircle the Earth would weigh less than 500 grams.",
        verified: true,
        source: "Materials Science Journal",
        year_discovered: 1994,
        interesting_rating: 9.0
    },
    {
        id: 26,
        category: "Animals",
        title: "Golden Poison Frog Toxicity",
        fact: "The golden poison frog contains enough toxin to kill 10-20 adult humans or about 10,000 mice. Just 2 micrograms—an amount that would fit on the head of a pin—is enough to kill a person.",
        verified: true,
        source: "Toxicology Research",
        year_discovered: 1978,
        interesting_rating: 9.2
    },
    {
        id: 27,
        category: "Animals",
        title: "Lobster Aging",
        fact: "Lobsters show no signs of aging or decline in fertility. They continue to grow and reproduce until they die, usually from disease or predation rather than old age.",
        verified: true,
        source: "Marine Biology Letters",
        year_discovered: 1998,
        interesting_rating: 8.9
    },
    {
        id: 28,
        category: "Animals",
        title: "Giraffe Blood Pressure",
        fact: "Giraffes have the highest blood pressure of any land animal—about 280/180 mm Hg—to push blood up their long necks to their brains. Special elastic blood vessels and valves prevent blood from rushing to their heads when they bend down to drink.",
        verified: true,
        source: "Comparative Physiology Journal",
        year_discovered: 1987,
        interesting_rating: 8.6
    },
    {
        id: 29,
        category: "Animals",
        title: "Parrotfish Sand Production",
        fact: "A single parrotfish can produce up to 840 pounds (380 kg) of sand per year as it grinds up coral with its beak-like teeth to extract algae. About 70% of the white sand on tropical beaches comes from parrotfish poop.",
        verified: true,
        source: "Marine Ecology Progress Series",
        year_discovered: 2010,
        interesting_rating: 8.7
    },
    {
        id: 30,
        category: "Animals",
        title: "Elephant Memory",
        fact: "Elephants have exceptional long-term memory and can recognize and track the location of up to 30 companions at a time. They can remember routes to water sources they visited once, decades earlier.",
        verified: true,
        source: "Animal Cognition Journal",
        year_discovered: 2008,
        interesting_rating: 9.0
    },
    {
        id: 31,
        category: "Animals",
        title: "Deep Sea Gigantism",
        fact: "Many deep-sea creatures exhibit gigantism. The giant isopod, related to pill bugs, can grow to 20 inches (50 cm) long, while deep-sea Japanese spider crabs have leg spans up to 12 feet (3.7 m).",
        verified: true,
        source: "Deep Sea Research",
        year_discovered: 1976,
        interesting_rating: 8.9
    },
    {
        id: 32,
        category: "Animals",
        title: "Flamingo Balance",
        fact: "Flamingos often stand on one leg because it's physiologically easier and requires less energy than standing on two. They have a unique locking mechanism in their legs that maintains balance without muscle effort.",
        verified: true,
        source: "Biology Letters",
        year_discovered: 2017,
        interesting_rating: 8.5
    },
    {
        id: 33,
        category: "Animals",
        title: "Electric Eel Voltage",
        fact: "Electric eels can generate electric shocks of up to 860 volts, enough to stun a horse. They contain specialized cells called electrocytes that function like tiny batteries connected in series.",
        verified: true,
        source: "Nature Communications",
        year_discovered: 2014,
        interesting_rating: 9.1
    },
    {
        id: 34,
        category: "Animals",
        title: "Koala Fingerprints",
        fact: "Koalas have fingerprints virtually indistinguishable from human fingerprints, even under an electron microscope. They're the only non-primates with true fingerprints.",
        verified: true,
        source: "Science Magazine",
        year_discovered: 1996,
        interesting_rating: 8.8
    }
];